channels:
  - conda-forge

dependencies:
  - python=3.11
  - jupyterhub-singleuser>=3.0,<4.0

  # Everyone wants to use nbgitpuller for everything, so let's do that
  - nbgitpuller=1.1.*
  # adding additional packages as requested
  - datascience==0.17.6
  - plotly==5.19.0
  - otter-grader==5.4.1
