channels:
  - conda-forge

dependencies:
  - nbgitpuller=1.2.*
  - datascience==0.17.5
  - plotly==5.19.*
  - conda-forge::python-kaleido=0.2.*
  - conda-forge::python-poppler
  - conda-forge::jupyter-resource-usage
  - conda-forge::pytorch
  - conda-forge::torchvision
  - conda-forge::ipyvuetify
  - pip
  - pip:
    - babypandas
    - pandas
    - ipywidgets==8.1.5
    - otter-grader==6.0.4
    - solara==1.38.0
    - nbconvert[webpdf]
    - pytest-playwright
    - install bash_kernel
