channels:
  - conda-forge

dependencies:
  - nbgitpuller=1.2.*
  - datascience==0.17.5
  - plotly==5.19.*
  - conda-forge::python-kaleido
  - conda-forge::python-poppler
  - conda-forge::jupyter-resource-usage
  - conda-forge::pytorch
  - conda-forge::torchvision
  - conda-forge::ipyvuetify
  - conda-forge::bash_kernel
  - conda-forge::sentence-transformers
  - pip
  - pip:
    - babypandas
    - pandas
    - ipywidgets==8.1.5
    - otter-grader[grading,plugins]==6.1.3
    - solara==1.38.0
    - nbconvert[webpdf]
    - pytest-playwright
    - ISLP==0.4.0
    - astroML
