channels:
  - conda-forge

dependencies:
  - nbgitpuller=1.2.*
  - datascience==0.17.*
  - plotly==5.19.*
  - otter-grader==5.4.*
  - conda-forge::python-kaleido=0.2.*
  - conda-forge::python-poppler
  - conda-forge::jupyter-resource-usage
  - conda-forge::pytorch
  - conda-forge::torchvision
  - conda-forge::ipyvuetify
  - pip
  - pip:
    - ISLP==0.3.22
    - babypandas==0.1.9
